GET http://localhost:3003/hello

### Valid /bmi
GET http://localhost:3003/bmi?weight=78&height=176

### Invalid /bmi
GET http://localhost:3003/bmi?weight=notanumber

### Valid /exerciese
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [7, 4, 3, 2, 2, 0, 0, 1],
  "target": 2
}

### Invalid /exercises
POST http://localhost:3003/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 2, 0, 1, 2, 4],
  "target": -1
}